# Use postgres/example user/password credentials
#version: "3.9"
#services:
#  postgres:
#    image: postgres:13.3
#    environment:
#      POSTGRES_DB: "shop"
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD: "admin"
#      PGDATA: "./db"
#    ports:
#      - "5432:5432"
#version: "3.9"
#services:
#  postgres:
#    image: postgres:13.3
#    environment:
#      POSTGRES_DB: "shop"
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD: "admin"
#      PGDATA: "./db"
#    ports:
#      - "5432:5432"
#  spring-boot-containers:
#    container_name: springboot
#    image: app-springboot-postgresql
#    build: ./
#    ports:
#      - "8080:8080"
#    links:
#      - postgres
#    environment:
#      SPRING_PROFILES_ACTIVE: dev
#      JAVA_HEAP_SIZE_MB: 1024

version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: "../dump"
    ports:
      - "5432:5432"
    #volumes:
    #  - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    #restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres
