# Use postgres/example user/password credentials
version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "shop"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "./db"
    ports:
      - "5432:5432"
